/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    FollowButton: typeof import('./src/components/FollowButton.vue')['default']
    GlassTabBar: typeof import('./src/components/GlassTabBar.vue')['default']
    ImageCarousel: typeof import('./src/components/ImageCarousel.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PdAvatar: typeof import('./src/components/ui/PdAvatar.vue')['default']
    PdBadge: typeof import('./src/components/ui/PdBadge.vue')['default']
    PdButton: typeof import('./src/components/ui/PdButton.vue')['default']
    PdCard: typeof import('./src/components/ui/PdCard.vue')['default']
    PdEmpty: typeof import('./src/components/ui/PdEmpty.vue')['default']
    PdInput: typeof import('./src/components/ui/PdInput.vue')['default']
    PdLoading: typeof import('./src/components/ui/PdLoading.vue')['default']
    PdNavBar: typeof import('./src/components/ui/PdNavBar.vue')['default']
    PostActionBar: typeof import('./src/components/PostActionBar.vue')['default']
    UniDatetimePicker: typeof import('@dcloudio/uni-ui/lib/uni-datetime-picker/uni-datetime-picker.vue')['default']
    UniIcons: typeof import('@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue')['default']
    UniPopup: typeof import('@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue')['default']
    UniTransition: typeof import('@dcloudio/uni-ui/lib/uni-transition/uni-transition.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
