"""add fake_sold and off_shelf_reason to point_products

Revision ID: 00e1df65fcaf
Revises: 4_7_004
Create Date: 2026-02-28

"""
from alembic import op
import sqlalchemy as sa
from alembic import context

# revision identifiers, used by Alembic.
revision = '00e1df65fcaf'
down_revision = '4_7_004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('point_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fake_sold', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('off_shelf_reason', sa.String(length=255), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('point_products', schema=None) as batch_op:
        batch_op.drop_column('off_shelf_reason')
        batch_op.drop_column('fake_sold')
