"""add missing user fields

Revision ID: 7923ea874537
Revises: 47f5da4ffdab
Create Date: 2026-02-24 19:55:10.679597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7923ea874537'
down_revision: Union[str, None] = '47f5da4ffdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_returns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False, comment='订单明细ID'),
    sa.Column('return_reason', sa.Enum('quality_issue', 'damaged', 'wrong_item', 'not_as_described', 'no_longer_needed', 'other', name='order_return_reason'), nullable=False, comment='退货原因'),
    sa.Column('return_description', sa.Text(), nullable=True, comment='退货说明'),
    sa.Column('images', sa.JSON(), nullable=True, comment='退货凭证图片'),
    sa.Column('return_type', sa.Enum('refund_only', 'replace', 'return_and_refund', name='order_return_type'), nullable=False, comment='退货类型'),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'shipped_back', 'received', 'processing', 'completed', name='order_return_status'), nullable=False, comment='退货状态'),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='退款金额(分)'),
    sa.Column('refund_transaction_id', sa.String(length=100), nullable=True, comment='退款交易ID'),
    sa.Column('requested_at', sa.DateTime(), nullable=False, comment='申请时间'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('admin_id', sa.String(length=36), nullable=True, comment='处理管理员ID'),
    sa.Column('admin_notes', sa.Text(), nullable=True, comment='管理员备注'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_returns_order_id'), 'order_returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_returns_status'), 'order_returns', ['status'], unique=False)
    op.create_table('order_shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('courier_code', sa.String(length=20), nullable=False, comment='物流公司代码'),
    sa.Column('courier_name', sa.String(length=50), nullable=False, comment='物流公司名称'),
    sa.Column('tracking_number', sa.String(length=50), nullable=False, comment='物流单号'),
    sa.Column('status', sa.Enum('pending', 'picked_up', 'in_transit', 'delivered', 'failed', name='order_shipment_status'), nullable=False, comment='发货状态'),
    sa.Column('shipped_at', sa.DateTime(), nullable=False, comment='发货时间'),
    sa.Column('delivered_at', sa.DateTime(), nullable=True, comment='签收时间'),
    sa.Column('tracking_info', sa.JSON(), nullable=True, comment='物流跟踪详情'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_shipments_order_id'), 'order_shipments', ['order_id'], unique=False)
    op.alter_column('app_themes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('check_ins', sa.Column('checkin_type', sa.String(length=50), nullable=True, comment='打卡类型: daily/weekly/milestone/special'))
    op.add_column('check_ins', sa.Column('reward_points', sa.Integer(), nullable=True, comment='奖励积分'))
    op.add_column('check_ins', sa.Column('streak_days', sa.Integer(), nullable=True, comment='连续打卡天数'))
    op.add_column('check_ins', sa.Column('mood', sa.String(length=50), nullable=True, comment='打卡时的心情'))
    op.add_column('check_ins', sa.Column('tags', sa.JSON(), nullable=True, comment='打卡标签 JSON'))
    op.drop_index('idx_comments_hot', table_name='comments')
    op.drop_index('idx_comments_post_parent', table_name='comments')
    op.drop_index('idx_comments_user', table_name='comments')
    op.drop_index('idx_comments_user_post', table_name='comments')
    op.drop_index('ix_comments_post_created', table_name='comments')
    op.drop_index('idx_follows_follower', table_name='follows')
    op.drop_index('idx_follows_following', table_name='follows')
    op.drop_index('idx_likes_user_target', table_name='likes')
    op.drop_index('ix_likes_target', table_name='likes')
    op.drop_index('ix_likes_unique', table_name='likes')
    op.create_index(op.f('ix_likes_target_id'), 'likes', ['target_id'], unique=False)
    op.drop_index('ix_orders_transaction', table_name='membership_orders')
    op.drop_index('ix_orders_user_status', table_name='membership_orders')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.alter_column('orders', 'points_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'shipping_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.drop_index('ix_orders_shipping_address_id', table_name='orders')
    op.add_column('posts', sa.Column('user_avatar', sa.String(length=255), nullable=True, comment='发帖时用户头像URL冗余'))
    op.add_column('posts', sa.Column('topic_ids', sa.JSON(), nullable=True, comment='关联话题ID列表，最多3个'))
    op.alter_column('posts', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('public', 'followers', 'private', name='post_visibility_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'public'"))
    op.alter_column('posts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('posts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('idx_posts_hot', table_name='posts')
    op.drop_index('idx_posts_tag', table_name='posts')
    op.drop_index('idx_posts_user', table_name='posts')
    op.drop_index('ix_posts_like_count', table_name='posts')
    op.drop_index('ix_posts_status_risk_created', table_name='posts')
    op.drop_index('ix_posts_user_created', table_name='posts')
    op.create_foreign_key(None, 'posts', 'topics', ['topic_id'], ['id'])
    op.alter_column('push_notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_push_notifications_user_id'), 'push_notifications', ['user_id'], unique=False)
    op.alter_column('risk_alerts', 'target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('risk_alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_risk_alerts_user_id'), 'risk_alerts', ['user_id'], unique=False)
    op.add_column('salary_records', sa.Column('is_arrears', sa.Integer(), nullable=True, comment='是否拖欠 (0=否, 1=是)'))
    op.add_column('salary_records', sa.Column('arrears_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='拖欠金额'))
    op.add_column('salary_records', sa.Column('mood_note', sa.Text(), nullable=True, comment='心情备注'))
    op.add_column('salary_records', sa.Column('mood_tags', sa.JSON(), nullable=True, comment='心情标签 JSON'))
    op.drop_index('idx_salary_records_user_payday', table_name='salary_records')
    op.alter_column('topics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True, comment='手机号（加密）'))
    op.add_column('users', sa.Column('phone_verified', sa.Integer(), nullable=True, comment='手机号是否验证'))
    op.add_column('users', sa.Column('invite_code', sa.String(length=12), nullable=True, comment='唯一邀请码'))
    op.add_column('users', sa.Column('invited_by', sa.String(length=36), nullable=True, comment='邀请者ID'))
    op.drop_index('idx_users_deactivated_at', table_name='users')
    op.drop_index('ix_users_status_created', table_name='users')
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.create_index(op.f('ix_users_invited_by'), 'users', ['invited_by'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_invited_by'), table_name='users')
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.create_index('ix_users_status_created', 'users', ['status', 'created_at'], unique=False)
    op.create_index('idx_users_deactivated_at', 'users', ['deactivated_at'], unique=False)
    op.drop_column('users', 'invited_by')
    op.drop_column('users', 'invite_code')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'phone_number')
    op.alter_column('topics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('idx_salary_records_user_payday', 'salary_records', ['user_id', 'payday_date'], unique=False)
    op.drop_column('salary_records', 'mood_tags')
    op.drop_column('salary_records', 'mood_note')
    op.drop_column('salary_records', 'arrears_amount')
    op.drop_column('salary_records', 'is_arrears')
    op.drop_index(op.f('ix_risk_alerts_user_id'), table_name='risk_alerts')
    op.alter_column('risk_alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('risk_alerts', 'target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_push_notifications_user_id'), table_name='push_notifications')
    op.alter_column('push_notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index('ix_posts_user_created', 'posts', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_posts_status_risk_created', 'posts', ['status', 'risk_status', 'created_at'], unique=False)
    op.create_index('ix_posts_like_count', 'posts', ['like_count'], unique=False)
    op.create_index('idx_posts_user', 'posts', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_posts_tag', 'posts', ['type', 'city', 'industry', 'created_at'], unique=False)
    op.create_index('idx_posts_hot', 'posts', ['type', 'status', 'risk_status', 'like_count', 'created_at'], unique=False)
    op.alter_column('posts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('posts', 'visibility',
               existing_type=sa.Enum('public', 'followers', 'private', name='post_visibility_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'public'"))
    op.drop_column('posts', 'topic_ids')
    op.drop_column('posts', 'user_avatar')
    op.create_index('ix_orders_shipping_address_id', 'orders', ['shipping_address_id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('orders', 'shipping_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'points_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_orders_user_status', 'membership_orders', ['user_id', 'status'], unique=False)
    op.create_index('ix_orders_transaction', 'membership_orders', ['transaction_id'], unique=False)
    op.drop_index(op.f('ix_likes_target_id'), table_name='likes')
    op.create_index('ix_likes_unique', 'likes', ['user_id', 'target_type', 'target_id'], unique=False)
    op.create_index('ix_likes_target', 'likes', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_likes_user_target', 'likes', ['user_id', 'target_id', 'target_type'], unique=False)
    op.create_index('idx_follows_following', 'follows', ['following_id'], unique=False)
    op.create_index('idx_follows_follower', 'follows', ['follower_id'], unique=False)
    op.create_index('ix_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index('idx_comments_user_post', 'comments', ['user_id', 'post_id'], unique=False)
    op.create_index('idx_comments_user', 'comments', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_comments_post_parent', 'comments', ['post_id'], unique=False)
    op.create_index('idx_comments_hot', 'comments', ['post_id', 'created_at'], unique=False)
    op.drop_column('check_ins', 'tags')
    op.drop_column('check_ins', 'mood')
    op.drop_column('check_ins', 'streak_days')
    op.drop_column('check_ins', 'reward_points')
    op.drop_column('check_ins', 'checkin_type')
    op.alter_column('app_themes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_order_shipments_order_id'), table_name='order_shipments')
    op.drop_table('order_shipments')
    op.drop_index(op.f('ix_order_returns_status'), table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_order_id'), table_name='order_returns')
    op.drop_table('order_returns')
    # ### end Alembic commands ###
