"""add topic_ids field to posts table

Revision ID: a19f4f22cb92
Revises: 4_7_002
Create Date: 2026-02-23 19:17:47.634188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a19f4f22cb92'
down_revision: Union[str, None] = '4_7_003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_qrcodemapping_expires_at', table_name='qrcode_mappings')
    op.drop_index('idx_qrcodemapping_short_code', table_name='qrcode_mappings')
    op.drop_table('qrcode_mappings')
    op.alter_column('ability_point_transactions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_apt_created_at', table_name='ability_point_transactions')
    op.drop_index('idx_apt_transaction_type', table_name='ability_point_transactions')
    op.drop_index('idx_apt_user_id', table_name='ability_point_transactions')
    op.create_index(op.f('ix_ability_point_transactions_user_id'), 'ability_point_transactions', ['user_id'], unique=False)
    op.drop_constraint('apt_user_fk', 'ability_point_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'ability_point_transactions', 'users', ['user_id'], ['id'])
    op.drop_column('ability_point_transactions', 'metadata')
    op.alter_column('ability_points', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ability_points', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_ap_level', table_name='ability_points')
    op.drop_index('idx_ap_user_id', table_name='ability_points')
    op.create_index(op.f('ix_ability_points_user_id'), 'ability_points', ['user_id'], unique=True)
    op.drop_constraint('ap_user_fk', 'ability_points', type_='foreignkey')
    op.create_foreign_key(None, 'ability_points', 'users', ['user_id'], ['id'])
    op.alter_column('app_themes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('idx_checkin_type', table_name='check_ins')
    op.drop_index('idx_comments_hot', table_name='comments')
    op.drop_index('idx_comments_post_parent', table_name='comments')
    op.drop_index('idx_comments_user', table_name='comments')
    op.drop_index('idx_comments_user_post', table_name='comments')
    op.drop_index('ix_comments_post_created', table_name='comments')
    op.alter_column('expense_records', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_index('idx_expense_user_date', 'expense_records', ['user_id', 'expense_date'], unique=False)
    op.drop_index('idx_follows_follower', table_name='follows')
    op.drop_index('idx_follows_following', table_name='follows')
    op.drop_index('idx_likes_user_target', table_name='likes')
    op.drop_index('ix_likes_target', table_name='likes')
    op.drop_index('ix_likes_unique', table_name='likes')
    op.create_index(op.f('ix_likes_target_id'), 'likes', ['target_id'], unique=False)
    op.drop_index('ix_orders_transaction', table_name='membership_orders')
    op.drop_index('ix_orders_user_status', table_name='membership_orders')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_constraint('uq_phone_lookup_hash', 'phone_lookup', type_='unique')
    op.create_index(op.f('ix_phone_lookup_phone_hash'), 'phone_lookup', ['phone_hash'], unique=True)
    op.create_index(op.f('ix_phone_lookup_user_id'), 'phone_lookup', ['user_id'], unique=False)
    op.alter_column('point_orders', 'processed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('point_orders', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('point_orders', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('ix_point_orders_created_at', table_name='point_orders')
    op.drop_index('ix_point_orders_product_id', table_name='point_orders')
    op.drop_index('ix_point_orders_status', table_name='point_orders')
    op.drop_index('ix_point_orders_order_number', table_name='point_orders')
    op.create_index(op.f('ix_point_orders_order_number'), 'point_orders', ['order_number'], unique=True)
    op.drop_constraint('po_admin_fk', 'point_orders', type_='foreignkey')
    op.drop_constraint('po_product_fk', 'point_orders', type_='foreignkey')
    op.drop_constraint('po_user_fk', 'point_orders', type_='foreignkey')
    op.create_foreign_key(None, 'point_orders', 'point_products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'point_orders', 'admin_users', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'point_orders', 'users', ['user_id'], ['id'])
    op.alter_column('point_products', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('point_products', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('ix_point_products_category', table_name='point_products')
    op.drop_index('ix_point_products_is_active', table_name='point_products')
    op.drop_index('ix_point_products_sort_order', table_name='point_products')
    op.alter_column('point_redemptions', 'processed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('point_redemptions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('point_redemptions', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_pr_reward_type', table_name='point_redemptions')
    op.drop_index('idx_pr_status', table_name='point_redemptions')
    op.drop_index('idx_pr_user_id', table_name='point_redemptions')
    op.create_index(op.f('ix_point_redemptions_user_id'), 'point_redemptions', ['user_id'], unique=False)
    op.drop_constraint('pr_user_fk', 'point_redemptions', type_='foreignkey')
    op.create_foreign_key(None, 'point_redemptions', 'users', ['user_id'], ['id'])
    op.add_column('posts', sa.Column('topic_ids', sa.JSON(), nullable=True, comment='关联话题ID列表，最多3个'))
    op.alter_column('posts', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('public', 'followers', 'private', name='post_visibility_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'public'"))
    op.drop_index('idx_posts_hot', table_name='posts')
    op.drop_index('idx_posts_tag', table_name='posts')
    op.drop_index('idx_posts_user', table_name='posts')
    op.drop_index('ix_posts_like_count', table_name='posts')
    op.drop_index('ix_posts_status_risk_created', table_name='posts')
    op.drop_index('ix_posts_user_created', table_name='posts')
    op.create_foreign_key(None, 'posts', 'topics', ['topic_id'], ['id'])
    op.alter_column('push_notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_push_notifications_user_id'), 'push_notifications', ['user_id'], unique=False)
    op.alter_column('risk_alerts', 'target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('risk_alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_risk_alerts_user_id'), 'risk_alerts', ['user_id'], unique=False)
    op.drop_index('idx_salary_is_arrears', table_name='salary_records')
    op.drop_index('idx_salary_records_user_payday', table_name='salary_records')
    op.drop_index('idx_salary_usage_records_id', table_name='salary_usage_records')
    op.drop_index('idx_salary_usage_records_salary_record_id', table_name='salary_usage_records')
    op.drop_index('idx_salary_usage_records_usage_date', table_name='salary_usage_records')
    op.drop_index('idx_salary_usage_records_usage_type', table_name='salary_usage_records')
    op.drop_index('idx_salary_usage_records_user_id', table_name='salary_usage_records')
    op.create_index(op.f('ix_salary_usage_records_salary_record_id'), 'salary_usage_records', ['salary_record_id'], unique=False)
    op.create_index(op.f('ix_salary_usage_records_usage_date'), 'salary_usage_records', ['usage_date'], unique=False)
    op.create_index(op.f('ix_salary_usage_records_usage_type'), 'salary_usage_records', ['usage_type'], unique=False)
    op.create_index(op.f('ix_salary_usage_records_user_id'), 'salary_usage_records', ['user_id'], unique=False)
    op.alter_column('savings_goals', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('savings_goals', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('savings_goals', 'completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_sg_category', table_name='savings_goals')
    op.drop_index('idx_sg_status', table_name='savings_goals')
    op.drop_index('idx_sg_user_id', table_name='savings_goals')
    op.create_index(op.f('ix_savings_goals_user_id'), 'savings_goals', ['user_id'], unique=False)
    op.drop_constraint('sg_user_fk', 'savings_goals', type_='foreignkey')
    op.create_foreign_key(None, 'savings_goals', 'users', ['user_id'], ['id'])
    op.alter_column('topics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_invitations', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('user_invitations', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('uq_user_invitations_invitee', table_name='user_invitations')
    op.drop_index('ix_user_invitations_invitee_id', table_name='user_invitations')
    op.create_index(op.f('ix_user_invitations_invitee_id'), 'user_invitations', ['invitee_id'], unique=True)
    op.create_foreign_key(None, 'user_invitations', 'users', ['inviter_id'], ['id'])
    op.create_foreign_key(None, 'user_invitations', 'users', ['invitee_id'], ['id'])
    op.drop_index('idx_users_deactivated_at', table_name='users')
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_index('ix_users_status_created', table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index('ix_users_status_created', 'users', ['status', 'created_at'], unique=False)
    op.create_index('idx_users_phone', 'users', ['phone_number'], unique=False)
    op.create_index('idx_users_deactivated_at', 'users', ['deactivated_at'], unique=False)
    op.drop_constraint(None, 'user_invitations', type_='foreignkey')
    op.drop_constraint(None, 'user_invitations', type_='foreignkey')
    op.drop_index(op.f('ix_user_invitations_invitee_id'), table_name='user_invitations')
    op.create_index('ix_user_invitations_invitee_id', 'user_invitations', ['invitee_id'], unique=False)
    op.create_index('uq_user_invitations_invitee', 'user_invitations', ['invitee_id'], unique=False)
    op.alter_column('user_invitations', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_invitations', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('topics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'savings_goals', type_='foreignkey')
    op.create_foreign_key('sg_user_fk', 'savings_goals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_savings_goals_user_id'), table_name='savings_goals')
    op.create_index('idx_sg_user_id', 'savings_goals', ['user_id'], unique=False)
    op.create_index('idx_sg_status', 'savings_goals', ['status'], unique=False)
    op.create_index('idx_sg_category', 'savings_goals', ['category'], unique=False)
    op.alter_column('savings_goals', 'completed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('savings_goals', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('savings_goals', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_salary_usage_records_user_id'), table_name='salary_usage_records')
    op.drop_index(op.f('ix_salary_usage_records_usage_type'), table_name='salary_usage_records')
    op.drop_index(op.f('ix_salary_usage_records_usage_date'), table_name='salary_usage_records')
    op.drop_index(op.f('ix_salary_usage_records_salary_record_id'), table_name='salary_usage_records')
    op.create_index('idx_salary_usage_records_user_id', 'salary_usage_records', ['user_id'], unique=False)
    op.create_index('idx_salary_usage_records_usage_type', 'salary_usage_records', ['usage_type'], unique=False)
    op.create_index('idx_salary_usage_records_usage_date', 'salary_usage_records', ['usage_date'], unique=False)
    op.create_index('idx_salary_usage_records_salary_record_id', 'salary_usage_records', ['salary_record_id'], unique=False)
    op.create_index('idx_salary_usage_records_id', 'salary_usage_records', ['id'], unique=False)
    op.create_index('idx_salary_records_user_payday', 'salary_records', ['user_id', 'payday_date'], unique=False)
    op.create_index('idx_salary_is_arrears', 'salary_records', ['is_arrears'], unique=False)
    op.drop_index(op.f('ix_risk_alerts_user_id'), table_name='risk_alerts')
    op.alter_column('risk_alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('risk_alerts', 'target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_push_notifications_user_id'), table_name='push_notifications')
    op.alter_column('push_notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index('ix_posts_user_created', 'posts', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_posts_status_risk_created', 'posts', ['status', 'risk_status', 'created_at'], unique=False)
    op.create_index('ix_posts_like_count', 'posts', ['like_count'], unique=False)
    op.create_index('idx_posts_user', 'posts', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_posts_tag', 'posts', ['type', 'city', 'industry', 'created_at'], unique=False)
    op.create_index('idx_posts_hot', 'posts', ['type', 'status', 'risk_status', 'like_count', 'created_at'], unique=False)
    op.alter_column('posts', 'visibility',
               existing_type=sa.Enum('public', 'followers', 'private', name='post_visibility_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'public'"))
    op.drop_column('posts', 'topic_ids')
    op.drop_constraint(None, 'point_redemptions', type_='foreignkey')
    op.create_foreign_key('pr_user_fk', 'point_redemptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_point_redemptions_user_id'), table_name='point_redemptions')
    op.create_index('idx_pr_user_id', 'point_redemptions', ['user_id'], unique=False)
    op.create_index('idx_pr_status', 'point_redemptions', ['status'], unique=False)
    op.create_index('idx_pr_reward_type', 'point_redemptions', ['reward_type'], unique=False)
    op.alter_column('point_redemptions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('point_redemptions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('point_redemptions', 'processed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.create_index('ix_point_products_sort_order', 'point_products', ['sort_order'], unique=False)
    op.create_index('ix_point_products_is_active', 'point_products', ['is_active'], unique=False)
    op.create_index('ix_point_products_category', 'point_products', ['category'], unique=False)
    op.alter_column('point_products', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('point_products', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'point_orders', type_='foreignkey')
    op.drop_constraint(None, 'point_orders', type_='foreignkey')
    op.drop_constraint(None, 'point_orders', type_='foreignkey')
    op.create_foreign_key('po_user_fk', 'point_orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('po_product_fk', 'point_orders', 'point_products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('po_admin_fk', 'point_orders', 'admin_users', ['admin_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_point_orders_order_number'), table_name='point_orders')
    op.create_index('ix_point_orders_order_number', 'point_orders', ['order_number'], unique=False)
    op.create_index('ix_point_orders_status', 'point_orders', ['status'], unique=False)
    op.create_index('ix_point_orders_product_id', 'point_orders', ['product_id'], unique=False)
    op.create_index('ix_point_orders_created_at', 'point_orders', ['created_at'], unique=False)
    op.alter_column('point_orders', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('point_orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('point_orders', 'processed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_phone_lookup_user_id'), table_name='phone_lookup')
    op.drop_index(op.f('ix_phone_lookup_phone_hash'), table_name='phone_lookup')
    op.create_unique_constraint('uq_phone_lookup_hash', 'phone_lookup', ['phone_hash'])
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_orders_user_status', 'membership_orders', ['user_id', 'status'], unique=False)
    op.create_index('ix_orders_transaction', 'membership_orders', ['transaction_id'], unique=False)
    op.drop_index(op.f('ix_likes_target_id'), table_name='likes')
    op.create_index('ix_likes_unique', 'likes', ['user_id', 'target_type', 'target_id'], unique=False)
    op.create_index('ix_likes_target', 'likes', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_likes_user_target', 'likes', ['user_id', 'target_id', 'target_type'], unique=False)
    op.create_index('idx_follows_following', 'follows', ['following_id'], unique=False)
    op.create_index('idx_follows_follower', 'follows', ['follower_id'], unique=False)
    op.drop_index('idx_expense_user_date', table_name='expense_records')
    op.alter_column('expense_records', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index('ix_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index('idx_comments_user_post', 'comments', ['user_id', 'post_id'], unique=False)
    op.create_index('idx_comments_user', 'comments', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_comments_post_parent', 'comments', ['post_id'], unique=False)
    op.create_index('idx_comments_hot', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index('idx_checkin_type', 'check_ins', ['checkin_type'], unique=False)
    op.alter_column('app_themes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'ability_points', type_='foreignkey')
    op.create_foreign_key('ap_user_fk', 'ability_points', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ability_points_user_id'), table_name='ability_points')
    op.create_index('idx_ap_user_id', 'ability_points', ['user_id'], unique=False)
    op.create_index('idx_ap_level', 'ability_points', ['level'], unique=False)
    op.alter_column('ability_points', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ability_points', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('ability_point_transactions', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'ability_point_transactions', type_='foreignkey')
    op.create_foreign_key('apt_user_fk', 'ability_point_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ability_point_transactions_user_id'), table_name='ability_point_transactions')
    op.create_index('idx_apt_user_id', 'ability_point_transactions', ['user_id'], unique=False)
    op.create_index('idx_apt_transaction_type', 'ability_point_transactions', ['transaction_type'], unique=False)
    op.create_index('idx_apt_created_at', 'ability_point_transactions', ['created_at'], unique=False)
    op.alter_column('ability_point_transactions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_table('qrcode_mappings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('short_code', sa.VARCHAR(length=16), nullable=False),
    sa.Column('page', sa.VARCHAR(length=200), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('scan_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qrcodemapping_short_code', 'qrcode_mappings', ['short_code'], unique=False)
    op.create_index('idx_qrcodemapping_expires_at', 'qrcode_mappings', ['expires_at'], unique=False)
    # ### end Alembic commands ###
