"""create address and shipping tables

Revision ID: a86ed29cae9c
Revises: 0bb92b276103
Create Date: 2026-02-24 09:38:43.155115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86ed29cae9c'
down_revision: Union[str, None] = '0bb92b276103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='区域代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='区域名称'),
    sa.Column('level', sa.String(length=10), nullable=False, comment='级别: province/city/district'),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['admin_regions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_regions_code'), 'admin_regions', ['code'], unique=True)
    op.create_index(op.f('ix_admin_regions_parent_code'), 'admin_regions', ['parent_code'], unique=False)
    op.create_table('courier_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='物流公司代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='物流公司名称'),
    sa.Column('website', sa.String(length=200), nullable=True, comment='官网'),
    sa.Column('tracking_url', sa.String(length=200), nullable=True, comment='物流查询URL'),
    sa.Column('supports_cod', sa.Boolean(), nullable=False, comment='支持货到付款'),
    sa.Column('supports_cold_chain', sa.Boolean(), nullable=False, comment='支持冷链'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('shipping_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='模板描述'),
    sa.Column('charge_type', sa.String(length=20), nullable=False, comment='计费方式: weight/quantity/fixed'),
    sa.Column('default_first_unit', sa.Integer(), nullable=False, comment='首件/首重(克或件)'),
    sa.Column('default_first_cost', sa.Integer(), nullable=False, comment='首件运费(分)'),
    sa.Column('default_continue_unit', sa.Integer(), nullable=False, comment='续件/续重(克或件)'),
    sa.Column('default_continue_cost', sa.Integer(), nullable=False, comment='续件运费(分)'),
    sa.Column('free_threshold', sa.Integer(), nullable=True, comment='包邮门槛(分)'),
    sa.Column('estimate_days_min', sa.Integer(), nullable=True, comment='预计到达最少天数'),
    sa.Column('estimate_days_max', sa.Integer(), nullable=True, comment='预计到达最多天数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_template_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('region_codes', sa.String(length=500), nullable=False, comment='区域代码列表(逗号分隔)'),
    sa.Column('region_names', sa.String(length=500), nullable=False, comment='区域名称列表(逗号分隔)'),
    sa.Column('first_unit', sa.Integer(), nullable=False, comment='首件/首重'),
    sa.Column('first_cost', sa.Integer(), nullable=False, comment='首件运费(分)'),
    sa.Column('continue_unit', sa.Integer(), nullable=False, comment='续件/续重'),
    sa.Column('continue_cost', sa.Integer(), nullable=False, comment='续件运费(分)'),
    sa.Column('free_threshold', sa.Integer(), nullable=True, comment='包邮门槛(分)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['shipping_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_template_regions_template_id'), 'shipping_template_regions', ['template_id'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('province_code', sa.String(length=20), nullable=False, comment='省份代码'),
    sa.Column('province_name', sa.String(length=50), nullable=False, comment='省份名称'),
    sa.Column('city_code', sa.String(length=20), nullable=False, comment='城市代码'),
    sa.Column('city_name', sa.String(length=50), nullable=False, comment='城市名称'),
    sa.Column('district_code', sa.String(length=20), nullable=False, comment='区县代码'),
    sa.Column('district_name', sa.String(length=50), nullable=False, comment='区县名称'),
    sa.Column('detailed_address', sa.String(length=200), nullable=False, comment='详细地址'),
    sa.Column('postal_code', sa.String(length=10), nullable=True, comment='邮政编码'),
    sa.Column('contact_name', sa.String(length=50), nullable=False, comment='联系人姓名'),
    sa.Column('contact_phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认地址'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_shipping_template_regions_template_id'), table_name='shipping_template_regions')
    op.drop_table('shipping_template_regions')
    op.drop_table('shipping_templates')
    op.drop_table('courier_companies')
    op.drop_index(op.f('ix_admin_regions_parent_code'), table_name='admin_regions')
    op.drop_index(op.f('ix_admin_regions_code'), table_name='admin_regions')
    op.drop_table('admin_regions')
    # ### end Alembic commands ###
