"""add point_returns table

Revision ID: f553d41dcbe7
Revises: d313b8b1a806
Create Date: 2026-02-24 21:47:29.418001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f553d41dcbe7'
down_revision: Union[str, None] = 'd313b8b1a806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='主题名称'),
    sa.Column('display_name', sa.String(length=50), nullable=False, comment='显示名称'),
    sa.Column('preview_color', sa.String(length=20), nullable=False, comment='预览色'),
    sa.Column('primary_color', sa.String(length=20), nullable=False, comment='主色调'),
    sa.Column('is_dark', sa.Integer(), nullable=False, comment='是否暗色主题'),
    sa.Column('is_system', sa.Integer(), nullable=False, comment='是否系统主题'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='商品名称'),
    sa.Column('description', sa.String(length=2000), nullable=True, comment='商品描述'),
    sa.Column('images', sa.JSON(), nullable=True, comment='商品图片URLs'),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('product_type', sa.Enum('point', 'cash', 'hybrid', name='product_type_enum'), nullable=False),
    sa.Column('item_type', sa.Enum('physical', 'virtual', 'bundle', name='item_type_enum'), nullable=False),
    sa.Column('bundle_type', sa.Enum('pre_configured', 'custom_builder', name='bundle_type_enum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('seo_keywords', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='分享用户ID'),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment='分享目标类型：post/salary/poster'),
    sa.Column('target_id', sa.String(length=36), nullable=True, comment='分享目标ID（帖子ID/工资记录ID等）'),
    sa.Column('share_channel', sa.String(length=20), nullable=False, comment='分享渠道：wechat_friend/wechat_moments'),
    sa.Column('share_status', sa.String(length=20), nullable=False, comment='分享状态：pending/success/failed'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='失败原因（仅当status=failed时有值）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    op.create_table('shipping_template_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('region_codes', sa.String(length=500), nullable=False, comment='区域代码列表(逗号分隔)'),
    sa.Column('region_names', sa.String(length=500), nullable=False, comment='区域名称列表(逗号分隔)'),
    sa.Column('first_unit', sa.Integer(), nullable=False, comment='首件/首重'),
    sa.Column('first_cost', sa.Integer(), nullable=False, comment='首件运费(分)'),
    sa.Column('continue_unit', sa.Integer(), nullable=False, comment='续件/续重'),
    sa.Column('continue_cost', sa.Integer(), nullable=False, comment='续件运费(分)'),
    sa.Column('free_threshold', sa.Integer(), nullable=True, comment='包邮门槛(分)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['shipping_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_template_regions_template_id'), 'shipping_template_regions', ['template_id'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('province_code', sa.String(length=20), nullable=False, comment='省份代码'),
    sa.Column('province_name', sa.String(length=50), nullable=False, comment='省份名称'),
    sa.Column('city_code', sa.String(length=20), nullable=False, comment='城市代码'),
    sa.Column('city_name', sa.String(length=50), nullable=False, comment='城市名称'),
    sa.Column('district_code', sa.String(length=20), nullable=False, comment='区县代码'),
    sa.Column('district_name', sa.String(length=50), nullable=False, comment='区县名称'),
    sa.Column('detailed_address', sa.String(length=200), nullable=False, comment='详细地址'),
    sa.Column('postal_code', sa.String(length=10), nullable=True, comment='邮政编码'),
    sa.Column('contact_name', sa.String(length=50), nullable=False, comment='联系人姓名'),
    sa.Column('contact_phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认地址'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount in fen/cents'),
    sa.Column('points_used', sa.Integer(), nullable=True, comment='Points used'),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Discount amount in fen/cents'),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='Shipping cost in fen/cents'),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Final amount in fen/cents'),
    sa.Column('payment_method', sa.Enum('wechat', 'alipay', 'points', 'hybrid', name='order_payment_method'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='order_payment_status'), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='Payment transaction ID'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='Payment timestamp'),
    sa.Column('status', sa.Enum('pending', 'paid', 'processing', 'shipped', 'delivered', 'completed', 'cancelled', 'refunding', 'refunded', name='order_status'), nullable=True),
    sa.Column('shipping_address_id', sa.String(length=36), nullable=True),
    sa.Column('shipping_template_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['user_addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('product_skus',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False, comment='SKU代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='SKU名称'),
    sa.Column('attributes', sa.JSON(), nullable=False, comment='规格属性'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='库存'),
    sa.Column('stock_unlimited', sa.Boolean(), nullable=False, comment='库存无限'),
    sa.Column('images', sa.JSON(), nullable=True, comment='SKU图片'),
    sa.Column('weight_grams', sa.Integer(), nullable=True, comment='重量(克)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_index(op.f('ix_product_skus_product_id'), 'product_skus', ['product_id'], unique=False)
    op.create_table('work_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('clock_in_time', sa.DateTime(), nullable=False, comment='打卡开始时间'),
    sa.Column('clock_out_time', sa.DateTime(), nullable=True, comment='打卡结束时间'),
    sa.Column('work_duration_minutes', sa.Integer(), nullable=True, comment='工作时长（分钟）'),
    sa.Column('work_type', sa.Enum('regular', 'overtime', 'weekend', 'holiday', name='work_type_enum'), nullable=False, comment='工作类型'),
    sa.Column('overtime_hours', sa.Numeric(precision=4, scale=2), nullable=False, comment='加班时长'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='工作地点'),
    sa.Column('company_name', sa.String(length=100), nullable=True, comment='公司名称'),
    sa.Column('mood', sa.String(length=20), nullable=True, comment='心情'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('content', sa.String(length=2000), nullable=False, comment='工作内容'),
    sa.Column('images', sa.JSON(), nullable=True, comment='图片列表'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index(op.f('ix_work_records_clock_in_time'), 'work_records', ['clock_in_time'], unique=False)
    op.create_index(op.f('ix_work_records_overtime_hours'), 'work_records', ['overtime_hours'], unique=False)
    op.create_index(op.f('ix_work_records_user_id'), 'work_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_work_records_work_type'), 'work_records', ['work_type'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sku_id', sa.String(length=36), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='Product name snapshot'),
    sa.Column('sku_name', sa.String(length=100), nullable=True, comment='SKU name snapshot'),
    sa.Column('product_image', sa.String(length=500), nullable=True, comment='Product image URL'),
    sa.Column('attributes', sa.JSON(), nullable=True, comment='SKU attributes snapshot'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Unit price in fen/cents'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantity'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='Subtotal in fen/cents'),
    sa.Column('bundle_components', sa.JSON(), nullable=True, comment='Bundle components snapshot'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('order_returns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False, comment='订单明细ID'),
    sa.Column('return_reason', sa.Enum('quality_issue', 'damaged', 'wrong_item', 'not_as_described', 'no_longer_needed', 'other', name='order_return_reason'), nullable=False, comment='退货原因'),
    sa.Column('return_description', sa.Text(), nullable=True, comment='退货说明'),
    sa.Column('images', sa.JSON(), nullable=True, comment='退货凭证图片'),
    sa.Column('return_type', sa.Enum('refund_only', 'replace', 'return_and_refund', name='order_return_type'), nullable=False, comment='退货类型'),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'shipped_back', 'received', 'processing', 'completed', name='order_return_status'), nullable=False, comment='退货状态'),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='退款金额(分)'),
    sa.Column('refund_transaction_id', sa.String(length=100), nullable=True, comment='退款交易ID'),
    sa.Column('requested_at', sa.DateTime(), nullable=False, comment='申请时间'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('admin_id', sa.String(length=36), nullable=True, comment='处理管理员ID'),
    sa.Column('admin_notes', sa.Text(), nullable=True, comment='管理员备注'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_returns_order_id'), 'order_returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_returns_status'), 'order_returns', ['status'], unique=False)
    op.create_table('order_shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('courier_code', sa.String(length=20), nullable=False, comment='物流公司代码'),
    sa.Column('courier_name', sa.String(length=50), nullable=False, comment='物流公司名称'),
    sa.Column('tracking_number', sa.String(length=50), nullable=False, comment='物流单号'),
    sa.Column('status', sa.Enum('pending', 'picked_up', 'in_transit', 'delivered', 'failed', name='order_shipment_status'), nullable=False, comment='发货状态'),
    sa.Column('shipped_at', sa.DateTime(), nullable=False, comment='发货时间'),
    sa.Column('delivered_at', sa.DateTime(), nullable=True, comment='签收时间'),
    sa.Column('tracking_info', sa.JSON(), nullable=True, comment='物流跟踪详情'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_shipments_order_id'), 'order_shipments', ['order_id'], unique=False)
    op.create_table('product_bundles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bundle_product_id', sa.String(length=36), nullable=False),
    sa.Column('component_product_id', sa.String(length=36), nullable=False),
    sa.Column('component_sku_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='是否必选'),
    sa.ForeignKeyConstraint(['bundle_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['component_sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_bundles_bundle_product_id'), 'product_bundles', ['bundle_product_id'], unique=False)
    op.create_index(op.f('ix_product_bundles_component_product_id'), 'product_bundles', ['component_product_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku_id', sa.String(length=36), nullable=False),
    sa.Column('price_type', sa.Enum('base', 'member', 'bulk', 'promotion', name='price_type_enum'), nullable=False),
    sa.Column('price_amount', sa.Integer(), nullable=False, comment='价格(分或积分)'),
    sa.Column('currency', sa.Enum('CNY', 'POINTS', name='price_currency_enum'), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False, comment='最小数量'),
    sa.Column('membership_level', sa.Integer(), nullable=True, comment='会员等级'),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_prices_sku_id'), 'product_prices', ['sku_id'], unique=False)
    op.drop_index('ix_qrcode_mappings_short_code', table_name='qrcode_mappings')
    op.drop_table('qrcode_mappings')
    op.alter_column('ability_point_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('ability_point_transactions', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ability_point_transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_ability_point_transactions_created_at', table_name='ability_point_transactions')
    op.alter_column('ability_points', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ability_points', 'available_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ability_points', 'level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('ability_points', 'total_earned',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ability_points', 'total_spent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ability_points', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('ability_points', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_ability_points_user_id', table_name='ability_points')
    op.create_index(op.f('ix_ability_points_user_id'), 'ability_points', ['user_id'], unique=True)
    op.alter_column('app_themes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('check_ins', 'checkin_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('check_ins', 'mood',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('check_ins', 'tags',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_comments_hot', table_name='comments')
    op.drop_index('idx_comments_post_parent', table_name='comments')
    op.drop_index('idx_comments_user', table_name='comments')
    op.drop_index('idx_comments_user_post', table_name='comments')
    op.drop_index('ix_comments_post_created', table_name='comments')
    op.alter_column('expense_records', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('expense_records', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_exp_category', table_name='expense_records')
    op.drop_index('idx_exp_expense_date', table_name='expense_records')
    op.drop_index('idx_exp_salary_record_id', table_name='expense_records')
    op.drop_index('idx_exp_user_id', table_name='expense_records')
    op.create_index('idx_expense_user_date', 'expense_records', ['user_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expense_records_category'), 'expense_records', ['category'], unique=False)
    op.create_index(op.f('ix_expense_records_expense_date'), 'expense_records', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expense_records_salary_record_id'), 'expense_records', ['salary_record_id'], unique=False)
    op.create_index(op.f('ix_expense_records_user_id'), 'expense_records', ['user_id'], unique=False)
    op.drop_constraint('exp_salary_fk', 'expense_records', type_='foreignkey')
    op.drop_constraint('exp_user_fk', 'expense_records', type_='foreignkey')
    op.create_foreign_key(None, 'expense_records', 'salary_records', ['salary_record_id'], ['id'])
    op.create_foreign_key(None, 'expense_records', 'users', ['user_id'], ['id'])
    op.drop_index('idx_follows_follower', table_name='follows')
    op.drop_index('idx_follows_following', table_name='follows')
    op.drop_index('idx_likes_user_target', table_name='likes')
    op.drop_index('ix_likes_target', table_name='likes')
    op.drop_index('ix_likes_unique', table_name='likes')
    op.create_index(op.f('ix_likes_target_id'), 'likes', ['target_id'], unique=False)
    op.drop_index('ix_orders_transaction', table_name='membership_orders')
    op.drop_index('ix_orders_user_status', table_name='membership_orders')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.alter_column('phone_lookup', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('phone_lookup', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('idx_phone_lookup_hash', 'phone_lookup', ['phone_hash'], unique=False)
    op.create_index('idx_phone_lookup_user_id', 'phone_lookup', ['user_id'], unique=False)
    op.create_foreign_key(None, 'phone_lookup', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('point_orders', 'order_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('point_orders', 'product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('point_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'completed', 'cancelled', 'refunded', name='point_order_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('point_orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('point_orders', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_point_orders_status', table_name='point_orders')
    op.create_index(op.f('ix_point_orders_order_number'), 'point_orders', ['order_number'], unique=True)
    op.create_foreign_key(None, 'point_orders', 'point_product_skus', ['sku_id'], ['id'])
    op.create_foreign_key(None, 'point_orders', 'order_shipments', ['shipment_id'], ['id'])
    op.create_foreign_key(None, 'point_orders', 'admin_users', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'point_orders', 'user_addresses', ['address_id'], ['id'])
    op.drop_constraint('uq_point_product_skus_code', 'point_product_skus', type_='unique')
    op.drop_constraint(None, 'point_product_skus', type_='foreignkey')
    op.create_foreign_key(None, 'point_product_skus', 'point_products', ['product_id'], ['id'])
    op.alter_column('point_products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('point_products', 'stock_unlimited',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('point_products', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('point_products', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('point_products', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('point_products', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_point_products_is_active', table_name='point_products')
    op.create_index(op.f('ix_point_products_category_id'), 'point_products', ['category_id'], unique=False)
    op.create_foreign_key(None, 'point_products', 'point_categories', ['category_id'], ['id'])
    op.alter_column('point_redemptions', 'reward_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('point_redemptions', 'reward_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('point_redemptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('point_redemptions', 'rejection_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('point_redemptions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('point_redemptions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_point_redemptions_status', table_name='point_redemptions')
    op.create_foreign_key(None, 'point_redemptions', 'admin_users', ['admin_id'], ['id'])
    op.drop_constraint(None, 'point_returns', type_='foreignkey')
    op.drop_constraint(None, 'point_returns', type_='foreignkey')
    op.create_foreign_key(None, 'point_returns', 'admin_users', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'point_returns', 'point_orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'point_specification_values', type_='foreignkey')
    op.create_foreign_key(None, 'point_specification_values', 'point_specifications', ['specification_id'], ['id'])
    op.drop_constraint(None, 'point_specifications', type_='foreignkey')
    op.create_foreign_key(None, 'point_specifications', 'point_products', ['product_id'], ['id'])
    op.alter_column('posts', 'topic_ids',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('posts', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('public', 'followers', 'private', name='post_visibility_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'public'"))
    op.alter_column('posts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('posts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('idx_posts_hot', table_name='posts')
    op.drop_index('idx_posts_tag', table_name='posts')
    op.drop_index('idx_posts_user', table_name='posts')
    op.drop_index('ix_posts_like_count', table_name='posts')
    op.drop_index('ix_posts_status_risk_created', table_name='posts')
    op.drop_index('ix_posts_user_created', table_name='posts')
    op.create_foreign_key(None, 'posts', 'topics', ['topic_id'], ['id'])
    op.alter_column('push_notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_push_notifications_user_id'), 'push_notifications', ['user_id'], unique=False)
    op.alter_column('risk_alerts', 'target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('risk_alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_risk_alerts_user_id'), 'risk_alerts', ['user_id'], unique=False)
    op.alter_column('salary_records', 'arrears_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('salary_records', 'mood_note',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('salary_records', 'mood_tags',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_salary_records_user_payday', table_name='salary_records')
    op.drop_index('idx_salary_usage_records_id', table_name='salary_usage_records')
    op.drop_index('idx_salary_usage_records_salary_record_id', table_name='salary_usage_records')
    op.drop_index('idx_salary_usage_records_usage_date', table_name='salary_usage_records')
    op.drop_index('idx_salary_usage_records_usage_type', table_name='salary_usage_records')
    op.drop_index('idx_salary_usage_records_user_id', table_name='salary_usage_records')
    op.create_index(op.f('ix_salary_usage_records_salary_record_id'), 'salary_usage_records', ['salary_record_id'], unique=False)
    op.create_index(op.f('ix_salary_usage_records_usage_date'), 'salary_usage_records', ['usage_date'], unique=False)
    op.create_index(op.f('ix_salary_usage_records_usage_type'), 'salary_usage_records', ['usage_type'], unique=False)
    op.create_index(op.f('ix_salary_usage_records_user_id'), 'salary_usage_records', ['user_id'], unique=False)
    op.alter_column('savings_goals', 'target_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('savings_goals', 'current_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('savings_goals', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('active', 'completed', 'cancelled', 'paused', name='savings_goal_status'),
               nullable=False,
               existing_server_default=sa.text("'active'"))
    op.alter_column('savings_goals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('savings_goals', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_savings_goals_status', table_name='savings_goals')
    op.alter_column('topics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_invitations', 'invitee_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('user_invitations', 'invite_code_used',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('user_invitations', 'inviter_points_rewarded',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_invitations', 'invitee_points_rewarded',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_invitations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_user_invitations_invitee_id', table_name='user_invitations')
    op.create_index(op.f('ix_user_invitations_invitee_id'), 'user_invitations', ['invitee_id'], unique=True)
    op.create_index('ix_user_invitations_inviter_invitee', 'user_invitations', ['inviter_id', 'invitee_id'], unique=False)
    op.alter_column('user_settings', 'privacy_profile',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_settings', 'allow_stranger_notice',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_settings', 'allow_comment',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'themes', ['theme_id'], ['id'])
    op.drop_index('idx_users_deactivated_at', table_name='users')
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_index('ix_users_status_created', table_name='users')
    op.drop_index('ix_users_invite_code', table_name='users')
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.create_index('ix_users_invite_code', 'users', ['invite_code'], unique=False)
    op.create_index('ix_users_status_created', 'users', ['status', 'created_at'], unique=False)
    op.create_index('idx_users_phone', 'users', ['phone_number'], unique=False)
    op.create_index('idx_users_deactivated_at', 'users', ['deactivated_at'], unique=False)
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'app_themes', ['theme_id'], ['id'])
    op.alter_column('user_settings', 'allow_comment',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_settings', 'allow_stranger_notice',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_settings', 'privacy_profile',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_user_invitations_inviter_invitee', table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_invitee_id'), table_name='user_invitations')
    op.create_index('ix_user_invitations_invitee_id', 'user_invitations', ['invitee_id'], unique=False)
    op.alter_column('user_invitations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_invitations', 'invitee_points_rewarded',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_invitations', 'inviter_points_rewarded',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_invitations', 'invite_code_used',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('user_invitations', 'invitee_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('topics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('ix_savings_goals_status', 'savings_goals', ['status'], unique=False)
    op.alter_column('savings_goals', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('savings_goals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('savings_goals', 'status',
               existing_type=sa.Enum('active', 'completed', 'cancelled', 'paused', name='savings_goal_status'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('savings_goals', 'current_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('savings_goals', 'target_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_salary_usage_records_user_id'), table_name='salary_usage_records')
    op.drop_index(op.f('ix_salary_usage_records_usage_type'), table_name='salary_usage_records')
    op.drop_index(op.f('ix_salary_usage_records_usage_date'), table_name='salary_usage_records')
    op.drop_index(op.f('ix_salary_usage_records_salary_record_id'), table_name='salary_usage_records')
    op.create_index('idx_salary_usage_records_user_id', 'salary_usage_records', ['user_id'], unique=False)
    op.create_index('idx_salary_usage_records_usage_type', 'salary_usage_records', ['usage_type'], unique=False)
    op.create_index('idx_salary_usage_records_usage_date', 'salary_usage_records', ['usage_date'], unique=False)
    op.create_index('idx_salary_usage_records_salary_record_id', 'salary_usage_records', ['salary_record_id'], unique=False)
    op.create_index('idx_salary_usage_records_id', 'salary_usage_records', ['id'], unique=False)
    op.create_index('idx_salary_records_user_payday', 'salary_records', ['user_id', 'payday_date'], unique=False)
    op.alter_column('salary_records', 'mood_tags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('salary_records', 'mood_note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('salary_records', 'arrears_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_risk_alerts_user_id'), table_name='risk_alerts')
    op.alter_column('risk_alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('risk_alerts', 'target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_push_notifications_user_id'), table_name='push_notifications')
    op.alter_column('push_notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index('ix_posts_user_created', 'posts', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_posts_status_risk_created', 'posts', ['status', 'risk_status', 'created_at'], unique=False)
    op.create_index('ix_posts_like_count', 'posts', ['like_count'], unique=False)
    op.create_index('idx_posts_user', 'posts', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_posts_tag', 'posts', ['type', 'city', 'industry', 'created_at'], unique=False)
    op.create_index('idx_posts_hot', 'posts', ['type', 'status', 'risk_status', 'like_count', 'created_at'], unique=False)
    op.alter_column('posts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('posts', 'visibility',
               existing_type=sa.Enum('public', 'followers', 'private', name='post_visibility_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'public'"))
    op.alter_column('posts', 'topic_ids',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_constraint(None, 'point_specifications', type_='foreignkey')
    op.create_foreign_key(None, 'point_specifications', 'point_products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'point_specification_values', type_='foreignkey')
    op.create_foreign_key(None, 'point_specification_values', 'point_specifications', ['specification_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'point_returns', type_='foreignkey')
    op.drop_constraint(None, 'point_returns', type_='foreignkey')
    op.create_foreign_key(None, 'point_returns', 'admin_users', ['admin_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'point_returns', 'point_orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'point_redemptions', type_='foreignkey')
    op.create_index('ix_point_redemptions_status', 'point_redemptions', ['status'], unique=False)
    op.alter_column('point_redemptions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('point_redemptions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('point_redemptions', 'rejection_reason',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('point_redemptions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('point_redemptions', 'reward_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('point_redemptions', 'reward_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'point_products', type_='foreignkey')
    op.drop_index(op.f('ix_point_products_category_id'), table_name='point_products')
    op.create_index('ix_point_products_is_active', 'point_products', ['is_active'], unique=False)
    op.alter_column('point_products', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('point_products', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('point_products', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('point_products', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('point_products', 'stock_unlimited',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('point_products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'point_product_skus', type_='foreignkey')
    op.create_foreign_key(None, 'point_product_skus', 'point_products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_point_product_skus_code', 'point_product_skus', ['sku_code'])
    op.drop_constraint(None, 'point_orders', type_='foreignkey')
    op.drop_constraint(None, 'point_orders', type_='foreignkey')
    op.drop_constraint(None, 'point_orders', type_='foreignkey')
    op.drop_constraint(None, 'point_orders', type_='foreignkey')
    op.drop_index(op.f('ix_point_orders_order_number'), table_name='point_orders')
    op.create_index('ix_point_orders_status', 'point_orders', ['status'], unique=False)
    op.alter_column('point_orders', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('point_orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('point_orders', 'status',
               existing_type=sa.Enum('pending', 'completed', 'cancelled', 'refunded', name='point_order_status'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('point_orders', 'product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('point_orders', 'order_number',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'phone_lookup', type_='foreignkey')
    op.drop_index('idx_phone_lookup_user_id', table_name='phone_lookup')
    op.drop_index('idx_phone_lookup_hash', table_name='phone_lookup')
    op.alter_column('phone_lookup', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('phone_lookup', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_orders_user_status', 'membership_orders', ['user_id', 'status'], unique=False)
    op.create_index('ix_orders_transaction', 'membership_orders', ['transaction_id'], unique=False)
    op.drop_index(op.f('ix_likes_target_id'), table_name='likes')
    op.create_index('ix_likes_unique', 'likes', ['user_id', 'target_type', 'target_id'], unique=False)
    op.create_index('ix_likes_target', 'likes', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_likes_user_target', 'likes', ['user_id', 'target_id', 'target_type'], unique=False)
    op.create_index('idx_follows_following', 'follows', ['following_id'], unique=False)
    op.create_index('idx_follows_follower', 'follows', ['follower_id'], unique=False)
    op.drop_constraint(None, 'expense_records', type_='foreignkey')
    op.drop_constraint(None, 'expense_records', type_='foreignkey')
    op.create_foreign_key('exp_user_fk', 'expense_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exp_salary_fk', 'expense_records', 'salary_records', ['salary_record_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_expense_records_user_id'), table_name='expense_records')
    op.drop_index(op.f('ix_expense_records_salary_record_id'), table_name='expense_records')
    op.drop_index(op.f('ix_expense_records_expense_date'), table_name='expense_records')
    op.drop_index(op.f('ix_expense_records_category'), table_name='expense_records')
    op.drop_index('idx_expense_user_date', table_name='expense_records')
    op.create_index('idx_exp_user_id', 'expense_records', ['user_id'], unique=False)
    op.create_index('idx_exp_salary_record_id', 'expense_records', ['salary_record_id'], unique=False)
    op.create_index('idx_exp_expense_date', 'expense_records', ['expense_date'], unique=False)
    op.create_index('idx_exp_category', 'expense_records', ['category'], unique=False)
    op.alter_column('expense_records', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('expense_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index('ix_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index('idx_comments_user_post', 'comments', ['user_id', 'post_id'], unique=False)
    op.create_index('idx_comments_user', 'comments', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_comments_post_parent', 'comments', ['post_id'], unique=False)
    op.create_index('idx_comments_hot', 'comments', ['post_id', 'created_at'], unique=False)
    op.alter_column('check_ins', 'tags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('check_ins', 'mood',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('check_ins', 'checkin_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('app_themes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_ability_points_user_id'), table_name='ability_points')
    op.create_index('ix_ability_points_user_id', 'ability_points', ['user_id'], unique=False)
    op.alter_column('ability_points', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ability_points', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ability_points', 'total_spent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ability_points', 'total_earned',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ability_points', 'level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('ability_points', 'available_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ability_points', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_ability_point_transactions_created_at', 'ability_point_transactions', ['created_at'], unique=False)
    op.alter_column('ability_point_transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ability_point_transactions', 'description',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ability_point_transactions', 'transaction_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('qrcode_mappings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('page', sa.VARCHAR(length=200), nullable=True),
    sa.Column('params', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('scan_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qrcode_mappings_short_code', 'qrcode_mappings', ['short_code'], unique=False)
    op.drop_index(op.f('ix_product_prices_sku_id'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_product_bundles_component_product_id'), table_name='product_bundles')
    op.drop_index(op.f('ix_product_bundles_bundle_product_id'), table_name='product_bundles')
    op.drop_table('product_bundles')
    op.drop_index(op.f('ix_order_shipments_order_id'), table_name='order_shipments')
    op.drop_table('order_shipments')
    op.drop_index(op.f('ix_order_returns_status'), table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_order_id'), table_name='order_returns')
    op.drop_table('order_returns')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_work_records_work_type'), table_name='work_records')
    op.drop_index(op.f('ix_work_records_user_id'), table_name='work_records')
    op.drop_index(op.f('ix_work_records_overtime_hours'), table_name='work_records')
    op.drop_index(op.f('ix_work_records_clock_in_time'), table_name='work_records')
    op.drop_table('work_records')
    op.drop_index(op.f('ix_product_skus_product_id'), table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_shipping_template_regions_template_id'), table_name='shipping_template_regions')
    op.drop_table('shipping_template_regions')
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('themes')
    # ### end Alembic commands ###
